#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 RouteWeave
#
# Regenerate the translation template from the _('…') strings in the views:
#
#   sh scripts/update-pot.sh           # rewrite po/templates/luci-app-treadle.pot
#   sh scripts/update-pot.sh --check   # fail when its strings differ (lint.sh)
#
# --check compares the set of strings only, so moving code around does not
# fail it; only a string added, changed or removed does. Needs GNU gettext
# (xgettext); it understands JavaScript string escapes and concatenation.

set -eu

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR" || exit 1
POT=po/templates/luci-app-treadle.pot

command -v xgettext >/dev/null 2>&1 || { echo "error: xgettext (GNU gettext) not found" >&2; exit 1; }

# The entries for every string, without xgettext's own header. The header is
# generated and then dropped, not omitted: without it xgettext declares no
# charset and mangles every non-ASCII string. Its warning about non-ASCII
# msgids, which LuCI apps use freely, is shown only if extraction fails.
extract() {
	err=$(mktemp)
	if ! find htdocs -name '*.js' | LC_ALL=C sort | xargs xgettext --language=JavaScript \
		--keyword=_ --from-code=UTF-8 --no-wrap --sort-by-file -o - 2>"$err" > "$err.pot"; then
		cat "$err" >&2
		rm -f "$err" "$err.pot"
		exit 1
	fi
	awk 'body { print; next } /^$/ { body = 1 }' "$err.pot"
	rm -f "$err" "$err.pot"
}

# One line per msgid, with any continuation lines joined on.
msgids() {
	awk '/^msgid /   { if (id != "") print id; id = substr($0, 7); inid = 1; next }
	     /^"/ && inid { id = id $0; next }
	                  { inid = 0 }
	     END          { if (id != "") print id }' | grep -v '^""$' | LC_ALL=C sort -u
}

if [ "${1:-}" = --check ]; then
	tmp=$(mktemp -d)
	trap 'rm -rf "$tmp"' EXIT
	extract | msgids > "$tmp/views"
	msgids < "$POT" > "$tmp/pot"
	if cmp -s "$tmp/views" "$tmp/pot"; then
		echo "$POT: $(wc -l < "$tmp/views" | tr -d ' ') strings, in step with the views"
		exit 0
	fi
	echo "$POT is out of date; run sh scripts/update-pot.sh"
	LC_ALL=C comm -23 "$tmp/views" "$tmp/pot" | sed 's/^/  missing: /'
	LC_ALL=C comm -13 "$tmp/views" "$tmp/pot" | sed 's/^/  stale:   /'
	exit 1
fi

{
	cat <<'EOF'
# Treadle LuCI app translation template
# Copyright (C) 2026 RouteWeave
# SPDX-License-Identifier: GPL-3.0-only
#
# Generated by scripts/update-pot.sh; do not edit by hand.
msgid ""
msgstr ""
"Project-Id-Version: luci-app-treadle\n"
"Report-Msgid-Bugs-To: https://github.com/routeweave/treadle/issues\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

EOF
	extract
} > "$POT"
echo "$POT: $(extract | msgids | wc -l | tr -d ' ') strings"
